ignore:
  - "tinynumpy/tinynumpy/tests/*"  # Ignore files in the tests directory
  - "tinynumpy/benchmark.py"

range: 70..90     # First number represents red, and second represents green
round: down       # up, down, or nearest